apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ecommerce
type: Opaque
stringData:
  DB_USER: ecommerce
  DB_PASSWORD: ecommerce_pass
  DB_NAME: ecommerce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  DB_HOST: "postgres"
  PAYMENT_URL: "http://payment:4000"
