---
- name: Download kubectl
  shell: |
    curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl

- name: Install kubectl
  shell: |
    chmod +x kubectl
    mv kubectl /usr/local/bin/
  args:
    creates: /usr/local/bin/kubectl

- name: Verify kubectl
  command: kubectl version --client
  register: kubectl_version

- debug:
    var: kubectl_version.stdout
